spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: ${SIZE}
        max-page-size: 100
      sort:
        sort-parameter: sort
debug: ${DEBUG}
server:
  port: ${PORT}
  error:
    include-stacktrace: on_trace_param

jwt:
  secret: ${JWT_SECRET}
  token-expire-time: ${JWT_TOKEN_EXPIRE_TIME}
  token-refresh-expire-time: ${JWT_TOKEN_REFRESH_EXPIRE_TIME}


